apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promotion-demo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPO_URL_PLACEHOLDER
    targetRevision: main
    path: k8s/promotion/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: promotion-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
