apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promotion-demo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andrewferdinandus/terraform-azure-aks.git
    targetRevision: main
    path: gitops/apps/dev/promotion-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: promotion-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
