apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incident-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPO_URL_PLACEHOLDER
    targetRevision: main
    path: k8s/incident
  destination:
    server: https://kubernetes.default.svc
    namespace: incident-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
