apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-demo
  namespace: promotion-qa
  labels:
    app: promotion-demo
    environment: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: promotion-demo
      environment: qa
  template:
    metadata:
      labels:
        app: promotion-demo
        environment: qa
    spec:
      nodeSelector:
        workload: user
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: content
          configMap:
            name: promotion-demo-content
