apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: professional-gitops-demo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/andrewferdinandus/aks-gitops-sample-app.git
  ref:
    branch: main
