apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-pr-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andrewferdinandus/aks-gitops-sample-app.git
    targetRevision: aiops-lab-03-github-pr-remediation
    path: k8s/aiops-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: aiops-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
