apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: professional-gitops-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andrewferdinandus/terraform-azure-aks.git
    targetRevision: main
    path: labs/professional/01-argocd-gitops/manifests
    directory:
      recurse: false
      exclude: argocd-application.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: professional-gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
