apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-devsecops-demo
  namespace: practitioner-gitlab-devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-devsecops-demo
  template:
    metadata:
      labels:
        app: gitlab-devsecops-demo
    spec:
      containers:
        - name: web
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
