apiVersion: v1
kind: Service
metadata:
  name: github-actions-demo
  namespace: practitioner-github-actions
spec:
  selector:
    app: github-actions-demo
  ports:
    - name: http
      port: 80
      targetPort: 80
