apiVersion: v1
kind: Service
metadata:
  name: promotion-demo
  namespace: promotion-dev
  labels:
    app: promotion-demo
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: promotion-demo
    environment: dev
  ports:
    - name: http
      port: 80
      targetPort: 80
